
services:
  cpp-server:
    image: serverimage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - testNetwork

networks:
  testNetwork:
    driver: overlay
    attachable: true

